#!/bin/sh
CMD=$@
DATA=$(cat)
DOMAINNAME=$(grep search /etc/resolv.conf)
NAMESERVER=$(grep nameserver /etc/resolv.conf)

case "$CMD" in
 *.dns*)
  NAMESERVER=$DATA
  ;;
 *.domain*)
  DOMAINNAME=$DATA
  ;;
esac

echo -e "$NAMESERVER\n$DOMAINNAME" > /etc/resolv.conf

